// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6B5MiBryDUCj3sonNGq3EjznXXmBTPM',
    appId: '1:240405501169:web:4c70a1ebc67ea7c1d70550',
    messagingSenderId: '240405501169',
    projectId: 'authentication-7f3da',
    authDomain: 'authentication-7f3da.firebaseapp.com',
    storageBucket: 'authentication-7f3da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43TM1Fmtfh6k33WZK2UooHfa1ZiUY9Co',
    appId: '1:240405501169:android:0fbee6e61f4e26b3d70550',
    messagingSenderId: '240405501169',
    projectId: 'authentication-7f3da',
    storageBucket: 'authentication-7f3da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-vaQwEwTwYtwea5wRKy5ojkIieL8uxU',
    appId: '1:240405501169:ios:45fde54d8b074b9ad70550',
    messagingSenderId: '240405501169',
    projectId: 'authentication-7f3da',
    storageBucket: 'authentication-7f3da.appspot.com',
    iosClientId: '240405501169-gbaf2e3jo6c4j1bf4vhur7478bpf3svn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notefusion',
  );
}
